[package]
name = "worgen_x"
version = "1.1.0"
edition = "2021"
authors = ["Xen0rInspire"]
license = "GNU General Public License v3.0"
description = "A powerful command line tool to generate relevant wordlists for password cracking. It can also generate random passwords with a good entropy."

[features]
cli = ["serde_json", "clap"]
gui = []

[dependencies]
rand = "0.8.5"
thiserror = "1.0.59"
num_cpus = "1.16.0"
serde_json = { version = "1.0.116", optional = true }
indicatif = "0.17.8"
clap = { version = "4.5.4", optional = true }