[package]
name = "worgen_x"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
cli = []
gui = []

[dependencies]
rand = "0.8.5"
thiserror = "1.0.47"
