[package]
name = "worgen_x"
version = "1.0.0"
edition = "2021"
authors = ["Xen0rInspire"]
license = "GNU General Public License v3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
cli = ["serde_json"]
gui = []

[dependencies]
rand = "0.8.5"
thiserror = "1.0.48"
serde_json = { version = "1.0.107", optional = true }